### ISSUE TITLE
User Prototype Testing 

### ISSUE THREAD

**Issue by zurda** [fac-15/Curenetics#24]
Hi, we're testing a prototype for an app to help cancer patients choose clinical trials.  Our prototype is for mobile, although we will be developing it for desktop as well. 
We will ask you to complete a couple of tasks and prompt you when needed. Please share your thoughts as you navigate through the app. For this initial test, we'll try to prompt as little as possible to get a true reaction to how easy you're finding the process. 

Imagine you're a 55 yo male prostate cancer patient looking for a clinical trial. 

1. View all the trials the app holds and download the first one as pdf. -> add downloaded feedback
2. Refine your search by answering some questions about your condition 
3. In the results page choose only phase 2 trials.

**Comment by zurda** [comment]
User testing results (needs editing): 

Thursday, 7 February 2019
12:04

Can you go to the next trial 

Download pdf worked as expected

For refining the condition - tried to change to filters 

Clicked the personalize trial 

Went into questionare. 

No option to no for levels, no explanation for each levels. IF you click level one - more information about levels 

Stage is different from phase 

Narrows it down. 

Phase 2, not stage. Most trials have a fixed phase. Type in key words 

If I'm going to take part in the trial, I would like to type in free text. 

When you're looking for a trial you want to know that it's applicable for you  and that it has results.

What is your diagnosis. Spread to other orangs - might make person not eligible. 

If it's phase 3 trial - patient would like to go. Phase one is this is my last chance. 

Age 
Mental capacity - being able to consent to a study 

Personalise inside the study rather than in the app. 

This app should be a GP kind of thing. Because of eligibility. 

Eligible - fill a form elsewhere. 

Is it more likely that it metastasises.

A patient would love a second opinion. Some patients are anxious. 
 When you're a patient in a hospital you're more likely to go to the hospital staff.

About the description: clicking eligibility. 

Summary of eligibility. Discard things that you're not eligible. 

Clicking button for full description 
Populate a small eligibility criteria for the patient. 

Where 
How many patients are already on the trial 
Currently recruiting or finished recruiting. 
Search by doctor 
Search by hospital 
Quick search -> narrow by age group or by hospital / location

**Comment by HStewart23** [comment]
###User testing results : 

###### How did you find the user interface ? 

It was easy to navigate, although the horizontal scroll direction is confusing. I think it would also be easy to navigate for older patients. 

###### What extra features would you add to the app if you could? 

An apply filters button so its clearer when they are in action.

###### How do you think it would make you feel if you were a patient and using this app?

More in control of my own sickness and more knowledgeable about what options are available to me. 

###### What do you think could be improved? 

- Some things might be a bit jargony. Patients might not be familiar with the stages in the trials. Not clear whether the stage is cancer or trail. What does it mean to be on a different phase?
- Instead of the GP you should contact a pi (person between clinicians and trials) because the practitioner is more likely to be able to respond quicker than either the clinicians or the person running the trail, this is important because there may be a short window for the study.

 

##### How do you feel about the amount of information you were asked to put in ? 

Good amount of information, any more and the patients might feel like they don't know enough to fill the form in. Might be nice if you had a link to clinical trail.gov for more info.


##### What affects how well a trial recruits?

- Clinician involvement means that trials recruit well. If clinicians mention the study to the patient and have someone follow up the patient are much more likely to join the trial. Those participants who show initiative are more likely to take part in the trial. 
- The set up of the study also effects who can get on it/ who wants to get on it. Some studies wont be of massive use to the patients so it depends if the patient wants to help research. 
- as long as travel reimbursement is possible it doesn't matter very much how far they have to travel. It matters more if its an extra visit from their clinic appointment. 


##### Do you like it ?

Yes ! It will be useful for clinicians because they can have all of the information that they need. They might take away the pdf and read it.
